### PR TITLE
Remind users to set graffiti, other doc updates

### PR DESCRIPTION
**Pull request by AmberKiso**
Documentation updates:
Remind new users set graffiti before mining.
Add -t option to miners:start command.
Add more details for some of the troubleshooting items.
Add encouragement to join testnet.
Add amount the Faucet sends.

## Summary
I've noticed several users ask about how they're not getting mining points. Turns out they didn't have a graffiti set.
Others reported why they're not mining. (They're not fully synced.)

Hopefully these changes will reduce the number of queries on Discord and improve the onboarding process.

## Testing Plan
Looked at the updated pages on localhost.

## Breaking Change

Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by AmberKiso** [comment]
Looking at the preview link, the installation guide link from the popdown "Testnet" banner at the top of the page takes me direct to the ironfish.network page, not the Vercel one.
But https://website-git-fork-amberkiso-clarify-graffiti-ironfish.vercel.app/docs/onboarding/iron-fish-cli works fine and the documentation changes look good. Not sure why that's happening.

**Comment by dguenther** [comment]
> Looking at the preview link, the installation guide link from the popdown "Testnet" banner at the top of the page takes me direct to the ironfish.network page, not the Vercel one. But https://website-git-fork-amberkiso-clarify-graffiti-ironfish.vercel.app/docs/onboarding/iron-fish-cli works fine and the documentation changes look good. Not sure why that's happening.

Looks like in `src\theme\Navbar\Testnet.js`, the Installation Guide link is hardcoded to go to ironfish.network. If you want to make it a relative link instead for easier testing, feel free! (it doesn't have to be in this PR)

**Review by dguenther — COMMENTED** [review]
This looks good to me! I realized when reading over this that we don't directly reference the testnet in the setup process anywhere. If you want to make one more change, I think it could be useful to add a reference to the `ironfish testnet` command somewhere (assuming the user has already signed up for a testnet account), because that will help make sure their graffiti and node names are set correctly.

If think that'll be a significant change and you'd rather do that in a separate PR, let me know and I'm good to merge this as is.

**Comment by AmberKiso** [comment]
Thank you!

Yes. I was surprised that command hasn't been documented either.
I'll play around with it right now and add think about how to best highlight it to new users.
I'm leaning towards throwing it into this PR, if you don't mind. (To make your [the team's] job easier with no having to wade through 1 more small PR.)

**Comment by AmberKiso** [comment]
One thing I noticed that could use a refresh:
In installation.md, there's an animated gif dropped into the page by

`<Terminal command={Ironfish} />`

Could you have someone update it to run `ironfish help` and display the newest command list?

**Comment by AmberKiso** [comment]
Done: relative banner link, testnet command added to CLI and referenced elsewhere. Sprinkled a few notes about needing a graffiti to get mining credit.

I decided on adding a "quick start" page after the installation one. It seems a little clunky in relation to the Get Started page (iron-fish-tutorial) only referencing 4 steps.

Maybe we make that 5 and add quick start to it? If so, let me know the icon name you want to use. Looks like QuickLinks.js is where that is set up.

**Comment by mat-if** [comment]
@AmberKiso (cc @dguenther) I'm going to go ahead and close this one since it's mostly outdated now. If you want to re-open a PR with just the parts that haven't been deprecated (like the faucet, needing graffiti for mining block points etc), I think that would be ok. Sorry for letting this one get outdated, that's on us. We're working to improve this process

**Pull request closed without merging**
