### PR TITLE
Interactive chain commands

### PR DESCRIPTION
**Pull request by aditya-manit**
## Summary
Added chain commands with Interactive session examples

## Testing Plan
Tested on local

## Breaking Change
No
~Is this a breaking change? If yes, add notes below on why this is breaking and
what additional work is required, if any.~

### CODE REVIEW

**Comment by dguenther** [comment]
The merge conflicts were fixed in another PR, but this should receive credit.

**Comment by aditya-manit** [comment]
Hi @dguenther I never received any testnet credits for this PR

**Comment by dguenther** [comment]
@aditya-manit Did you submit the PR using the form on our website? We should still be tracking submissions using that form and awarding points for them.

**Comment by aditya-manit** [comment]
Yes I did, but the points were not given when I checked my profile on tetsnet UI for phase 1

**Comment by aditya-manit** [comment]
Any updates on this @dguenther ??

**Comment by adi7dev** [comment]
@aditya-manit No submission was made for this PR.. I just checked the Phase 1 submissions.

**Comment by aditya-manit** [comment]
Hey @adi7dev not sure why, but in my docs I actually had marked it as "form filled"

Could you check for these as well, I didn't get points for any of this

## PR

[https://github.com/iron-fish/website/pull/149](https://github.com/iron-fish/website/pull/149)

[https://github.com/iron-fish/website/pull/148](https://github.com/iron-fish/website/pull/148)

## Bugs

[https://github.com/iron-fish/ironfish/issues/1002](https://github.com/iron-fish/ironfish/issues/1002)

[https://github.com/iron-fish/ironfish/issues/998](https://github.com/iron-fish/ironfish/issues/998)

[https://github.com/iron-fish/ironfish/issues/997](https://github.com/iron-fish/ironfish/issues/997)

**Comment by adi7dev** [comment]
@aditya-manit First off, do not tag every developer or team member on every single submission you've made. We've replied almost half a year ago on those, if not earlier.  
As or these submissions, 1002 is a duplicate but I'll check on the other 2 and get back to you soon. Need not bump, you'll probably hear from me in the next week. 
Also kindly use Discord for following-up instead of Github, thanks.

**Pull request closed without merging**
